config/routes.rb
Rails.application.routes.draw do

      resources :tasks do
        collection do
          get 'search'
        end
      end

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :find_item, only: [:edit, :update, :destroy, :show] #перед цими діями буде викликаний find_item

  def new # GET
    @task = Task.new
  end

  def create #POST
    @task = Task.create item_params
    redirect_to action: 'index'
  end

  def item_params #GET or POST
    params.require(:task).permit(:id, :text, :actual)
  end

  def index #GET запрос
    @tasks = Task.all
  end

  def edit #GET
  end

  def update #PUT
    @task.update_attributes item_params
    if @task.errors.empty?
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to action: 'index'
  end

  def show
  end

  def search
    search_key = params[:name]
    if search_key
      @tasks = Task.where('actual Like ?', "%#{search_key}%")
    end
  end

  private
  def find_item
    @task = Task.where(id: params[:id]).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoRTaskList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<p><%= f.label :text %><br>
  <%= f.text_field :text %></p>

<p><%= f.label :actual %><br>
  <%= f.text_field :actual %></p>


app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
    <%= render partial: 'form', locals: {f: f}%>
    <br>
    <%= f.submit 'Save' %>
<% end %>

app/views/tasks/index.html.erb
<h1>Hi</h1>
<% if @tasks.empty? %> <h2>Tasks list is empty</h2>
<% else %>
    <table>
      <tr>
        <th> Id </th>
        <th> Text </th>
        <th> Actual </th>
        <th> Edit </th>
        <th> Remove </th>
      </tr>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.id %></td>
          <td><%= task.text %></td>
          <td><%= task.actual %></td>
          <td><%= link_to 'edit', edit_task_path(task) %></td>
          <td><%= link_to 'remove', task_path(task), method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
      <% end %>
    </table>
<% end %>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
    <%= render partial: 'form', locals: {f: f}%>
    <br>
    <%= f.submit 'Create' %>
<% end %>

app/views/tasks/search.html.erb
<% if @tasks.empty? %>
    <h2>Please enter your search query:</h2>
    <form action="/tasks/search" method="get">
      <label for="search_key">Search word:</label>
      <input type="text" name="search_key" id="search_key">
      <button type="submit">Search...</button>
    </form>
<% else %>
    <h1>Search results</h1>
    <table border="1">
      <tr>
        <th>Id</th>
        <th>Text</th>
        <th>Actual</th>
        <th>Edit</th>
        <th>Remove</th>
      </tr>
      <% @tasks.each do |task| %>
          <tr>
            <td><%= task.id %></td>
            <td><%= task.text %></td>
            <td><%= task.actual %></td>
            <td><%= link_to 'edit', edit_task_path(task) %></td>
            <td><%= link_to 'remove', task_path(task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
    </table>
<% end %>

app/views/tasks/show.html.erb
<ul>
  <li><%= "ID: #{@task.id}"%></li>
  <li><%= "Text: #{@task.text}"%></li>
  <li><%= "Actual: #{@task.actual}"%></li>
</ul>